### ISSUE TITLE
WPA_Supplicant error

### ISSUE THREAD

**Issue by Hegz** [rhinstaller/dasbus#39]
Hi,

I'm using ubuntu 20.04 on a Raspberry pi 3b+  (python version 3.8.2, dasbus 1.3) and I'm getting the following error:

Traceback (most recent call last):
  File "/home/ubuntu/WiPiScanner/App/wpa_dbus.py", line 79, in <module>
    print(wpa_interface.SignalPoll())
  File "/home/ubuntu/WiPiScanner/venv/lib/python3.8/site-packages/dasbus/client/handler.py", line 444, in _call_method
    return self._get_method_reply(
  File "/home/ubuntu/WiPiScanner/venv/lib/python3.8/site-packages/dasbus/client/handler.py", line 476, in _get_method_reply
    return self._handle_method_error(error)
  File "/home/ubuntu/WiPiScanner/venv/lib/python3.8/site-packages/dasbus/client/handler.py", line 487, in _handle_method_error
    raise error
  File "/home/ubuntu/WiPiScanner/venv/lib/python3.8/site-packages/dasbus/client/handler.py", line 474, in _get_method_reply
    result = call(*args, **kwargs)
  File "/home/ubuntu/WiPiScanner/venv/lib/python3.8/site-packages/dasbus/client/handler.py", line 57, in sync_call
    return connection.call_sync(
gi.repository.GLib.Error: g-io-error-quark: Method “SignalPoll” returned type “(v)”, but expected “(a{sv})” (13)

and my code that is causing the issue:
`
for ap in AP_List:

  interface = wpa_supp.GetInterface('wlan0')
  wpa_interface = bus.get_proxy('fi.w1.wpa_supplicant1', interface)

  network_props = { 'bssid' : Variant('s', ap.bssid),
                    'ssid' : Variant('s', ap.essid),
                    'psk': Variant('s', Inspect_Set.get(ssid=ap.essid).psk)}

  network = wpa_interface.AddNetwork(network_props)

  wpa_interface.SelectNetwork(network);

  print('ssid:' + ap.essid + ' bssid:' + ap.bssid )

  while (wpa_interface.State != 'disconnected') & (wpa_interface.State != 'completed'):
    sleep(0.5)

  if wpa_interface.State == 'completed':
    print(wpa_interface.SignalPoll())
  wpa_interface.RemoveNetwork(network)
`
I'm new to python and dbus, so I'm really not sure what to make of it, or how to get past it...

**Comment by poncovka** [comment]
Hi, it looks to me like a bug in the DBus method `SignalPoll`. It is supposed to return a dictionary of variants, but it returns a variant. I suggest to report a bug for the Ubuntu package that provides `wpa_supplicant`. The only workaround is to use a different method if possible until the bug is fixed.

**Comment by poncovka** [comment]
Actually, you could try use the low-level API of dasbus as a workaround. It doesn't depend on the introspection of the DBus object that causes the error. It will probably look like this:

```
GLibClient.sync_call(
    bus.connection,
    'fi.w1.wpa_supplicant1',
    interface,
    "fi.w1.wpa_supplicant1.Interface",
    "SignalPoll",
    None,
    get_variant_type("(v)")
)
```

**Comment by Hegz** [comment]
Thanks that works great. :)

I've reported the bug to ubuntu anyway, although I don't expect much to come of it.

**Comment by poncovka** [comment]
In that case, I am closing the issue. I am glad it works :-)
