### ISSUE TITLE
Support for file descriptor passing

### ISSUE THREAD

**Issue by dogtopus** [rhinstaller/dasbus#65]
I'm looking into adding support for the "new" dbus API in PyBluez. In order to initiate a incoming connection with BlueZ's [Profile interface](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/profile-api.txt), BlueZ accepts the connection and passes the socket as a file descriptor with the `NewConnection` call. However this is not currently supported in dasbus.

Are there any plans to support file descriptor passing?

**Comment by poncovka** [comment]
Hi, it is definitely doable, but so far no one requested it. I will put it on my todo list, but this one can be tricky, so it can take some time.

**Comment by dogtopus** [comment]
Any updates?

**Comment by poncovka** [comment]
The support for Unix file descriptors was released in [dasbus-1.7](https://github.com/rhinstaller/dasbus/releases/tag/v1.7). There is an example in the [documentation](https://dasbus.readthedocs.io/en/latest/examples.html#support-for-unix-file-descriptors).
